<div class="suggestFormWrap" >
	<form action="" method="GET" name="search_word_inc">
		<input type="hidden" name="queryFromSuggest" />
		<!-- input type="hidden" name="{* $channelParam *}" value="{* channel *}" / -->
		<input type="text" name="query" id="query"
			value="<?php
				if ($ffparams->getQuery() == '' || $ffparams->isNavigation()) {
					echo $i18n->msg("searchbox_defaultText"), '" class="default';
				} else {
					echo htmlspecialchars($ffparams->getQuery());
				} ?>"
			autocomplete="off" />

		<input type="image" id="submit" src="<?php echo $i18n->msg('searchbox_submitButtonURL'); ?>"/>
		<div id="suggestLayer" class="suggestLayer"></div>
		<script language="JavaScript" type="text/javascript">
		<!--
				var suggest				= new FFSuggest();
				var searchURL			= 'suggest.php';
				var formname			= 'search_word_inc';
				var queryParamName		= 'query';
				var channelParamName	= 'channel';
				var channel				= '<?php echo $ffparams->getChannel(); ?>';
				var divLayername		= 'suggestLayer';
				var instanceName		= 'suggest';
				var debugMode			= false;
				var showImages          = false;
				suggest.init(searchURL, formname, queryParamName, divLayername, instanceName, debugMode, channelParamName, channel, showImages);
				document.onmousedown = suggest.hideLayerOutsideCall;
		// -->
		</script>
	</form>
</div>
