<?php
	if (!isset($fieldname)) {
		include 'fieldnamesConfig.php';
	}
	
	$articleNr   = $record->getValue($fieldname['artNo']);
	$title       = $record->getValue($fieldname['title']);
	$price       = $record->getValue($fieldname['price']);
	$description = $record->getValue($fieldname['description']);
	$imageUrl    = $record->getValue($fieldname['imageUrl']);
	$detailUrl   = $record->getValue($fieldname['detailUrl']);
	$sid         = '';
?>


<div class="productWrap">
	<div class="product">
		<div class="picture">
			<a href="<?php echo $detailUrl; ?>" onclick="<?php echo $util->createJavaScriptClickCode($record, $title, $sid, false); ?>">
				<img valign="top" src="<?php echo $imageUrl; ?>" alt="<?php echo $i18n->msg('product_noPicture'); ?>"
					title="<?php echo addslashes($title); ?>" onload="resizePicture(this, 120, 170)" onerror="imageNotFound(this)"
					onmouseover="TagToTip('descr<?php echo $articleNr; ?>', SHADOW, true)" onmouseout="UnTip()" />
			</a>
		</div>

		<div style="display:none">
			<span id="descr<?php echo $articleNr; ?>" class="hoverDescription">
				<p style="width:200px; font-weight: bold; margin-bottom: 2px;"><?php echo $title; ?></p>
				<p style="width:200px; text-align: right; margin-top: 0;">
					<?php echo $i18n->msg('product_articlenumber'); ?> <?php echo $articleNr; ?>
				</p>
				<p style="width:200px;">
				<?php
					echo mb_strimwidth($description, 0, 160, '..', 'UTF-8');
				?>
			</p>
			</span>
		</div>

		<div class="title">
			<a href="<?php echo $detailUrl; ?>" onclick="<?php echo $util->createJavaScriptClickCode($record, $title, $sid); ?>">
			<?php
				echo mb_strimwidth($title, 0, 23, '..', 'UTF-8');
			?>
			</a>
		</div>
		<div class="price"><?php echo $price, $i18n->msg('product_priceUnit'); ?></div>
	</div>
</div>